version: 2.1

orbs:
  node: circleci/node@5.0.3
  rn: react-native-community/react-native@7.1.1

commands:
  detox_build_ios:
    steps:
      - restore_cache:
          keys:
            - ios-build-cache-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: |
          # npm install -g detox-cli react-native-cli
          npx detox build e2e --configuration ios.release
      - save_cache:
          key: ios-build-cache-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ios/build/Build


jobs:
  detox_ios:
    executor:
      name: rn/macos
      xcode_version: 12.5.1
    steps:
      - checkout
      - rn/setup_macos_executor
      - rn/yarn_install:
          cache_folder: ~/.cache/yarn
      - rn/pod_install
      - rn/ios_simulator_start:
          device: iPhone 14 Pro
      - detox_build_ios
      - run: npx detox test e2e --configuration ios.release --cleanup --debug-synchronization 200 --record-videos all --take-screenshots all --record-logs all
      - store_artifacts:
          path: artifacts

workflows:
  test_and_distribute:
    jobs:
      - detox_ios
